FROM node:18-alpine
WORKDIR /workdir/frontend

ENV NODE_ENV=development

COPY package.json package-lock.json ./
RUN apk add --no-cache libc6-compat && npm ci

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
