name: Build and Deploy Green Container

on:
  push:
    branches:
      - release

env:
  FRONT_PROD1_PORT: 3001
  FRONT_PROD2_PORT: 3002
  BACK_PROD1_PORT: 8001
  BACK_PROD2_PORT: 8002
  FRONT_DOCKER_IMAGE: rimember/ringchat-frontend-prod:latest
  BACK_DOCKER_IMAGE: rimember/ringchat-backend-prod:latest
  FRONT_DOCKER_CONTAINER: frontend-green
  BACK_DOCKER_CONTAINER: backend-green

jobs:
  check-ports:
    runs-on: ubuntu-latest
    outputs:
      front-green-port: ${{ steps.green-ports.outputs.FRONT_GREEN_PORT }}
      back-green-port: ${{ steps.green-ports.outputs.BACK_GREEN_PORT }}
    steps:
      - name: Create frontend server ssh key file
        run: |
          echo "${{ secrets.FRONT_SERVER_SSH_KEY }}" > ~/fkey.pem
          chmod 400 ~/fkey.pem

      - name: Check frontend blue container port
        id: green-ports
        run: |
          FRONT_BLUE_PORT=$(ssh -i ~/fkey.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.FRONT_SERVER_HOST }} \
          "docker inspect --format='{{.HostConfig.PortBindings}}' frontend-blue | awk '{print \$2}' | awk -F '}' '{print \$1}'")

          echo "Current frontend blue container port: $FRONT_BLUE_PORT"

          if [ "$FRONT_BLUE_PORT" = "${{ env.FRONT_PROD1_PORT }}" ]; then
            echo "FRONT_GREEN_PORT=${{ env.FRONT_PROD2_PORT }}" >> $GITHUB_OUTPUT
            echo "BACK_GREEN_PORT=${{ env.BACK_PROD2_PORT }}" >> $GITHUB_OUTPUT
          else
            echo "FRONT_GREEN_PORT=${{ env.FRONT_PROD1_PORT }}" >> $GITHUB_OUTPUT
            echo "BACK_GREEN_PORT=${{ env.BACK_PROD1_PORT }}" >> $GITHUB_OUTPUT
          fi

  deploy-frontend-green:
    runs-on: ubuntu-latest
    needs: check-ports
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build frontend docker image
        run: docker build -t ${{ env.FRONT_DOCKER_IMAGE }} ./frontend

      - name: Push frontend docker image
        run: docker push ${{ env.FRONT_DOCKER_IMAGE }}

      - name: Deploy frontend green container on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          key: ${{ secrets.FRONT_SERVER_SSH_KEY }}
          host: ${{ secrets.FRONT_SERVER_HOST }}
          username: ubuntu
          script: |
            docker stop ${{ env.FRONT_DOCKER_CONTAINER }} || true
            docker rm ${{ env.FRONT_DOCKER_CONTAINER }} || true
            docker pull ${{ env.FRONT_DOCKER_IMAGE }}
            docker run -d --name ${{ env.FRONT_DOCKER_CONTAINER }} \
              -p ${{ needs.check-ports.outputs.front-green-port }}:3000 \
              ${{ env.FRONT_DOCKER_IMAGE }}

  deploy-backend-green:
    runs-on: ubuntu-latest
    needs: check-ports
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build backend docker image
        run: docker build -t ${{ env.BACK_DOCKER_IMAGE }} ./backend

      - name: Push backend docker image
        run: docker push ${{ env.BACK_DOCKER_IMAGE }}

      - name: Deploy backend green container on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          key: ${{ secrets.BACK_SERVER_SSH_KEY }}
          host: ${{ secrets.BACK_SERVER_HOST }}
          username: ubuntu
          script: |
            docker stop ${{ env.BACK_DOCKER_CONTAINER }} || true
            docker rm ${{ env.BACK_DOCKER_CONTAINER }} || true
            docker pull ${{ env.BACK_DOCKER_IMAGE }}
            docker run -d --name ${{ env.BACK_DOCKER_CONTAINER }} \
              -p ${{ needs.check-ports.outputs.back-green-port }}:8000 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY}} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY}} \
              ${{ env.BACK_DOCKER_IMAGE }}

  update-nginx-config:
    runs-on: ubuntu-latest
    needs: [check-ports, deploy-frontend-green, deploy-backend-green]
    steps:
      - name: Update Nginx config on server
        uses: appleboy/ssh-action@v1.1.0
        with:
          key: ${{ secrets.FRONT_SERVER_SSH_KEY }}
          host: ${{ secrets.FRONT_SERVER_HOST }}
          username: ubuntu
          script: |
            sudo sed -i "/upstream frontend_green {/,/}/s/:\([0-9]\+\);/:${{ needs.check-ports.outputs.front-green-port }};/" /etc/nginx/sites-available/ringchat.site
            sudo sed -i "/upstream backend_green {/,/}/s/:\([0-9]\+\);/:${{ needs.check-ports.outputs.back-green-port }};/" /etc/nginx/sites-available/ringchat.site
            sudo systemctl reload nginx
